server:
  port: 9006

spring:
  application:
    name: notification-service
  data:
    redis:
      host: redis
      port: 6379
  cache:
    type: redis
  kafka:
    bootstrap-servers: broker:9092
    producer:
      properties:
        auto.create.topics.enable: true
        default.replication.factor: 1
    consumer:
      group-id: notification-service
jwt:
  signerKey: "In this society, only those who work hard, diligently, and tirelessly will earn their share. Only by working can one eat. Those who expect to eat without working will end up eating sh*t."
  expirationMs: 69696969