apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: default
type: Opaque
data:
  signer-key: SW4gdGhpcyBzb2NpZXR5LCBvbmx5IHRob3NlIHdobyB3b3JrIGhhcmQsIGRpbGlnZW50bHksIGFuZCB0aXJlbGVzc2x5IHdpbGwgZWFybiB0aGVpciBzaGFyZS4gT25seSBieSB3b3JraW5nIGNhbiBvbmUgZWF0LiBUaG9zZSB3aG8gZXhwZWN0IHRvIGVhdCB3aXRob3V0IHdvcmtpbmcgd2lsbCBlbmQgdXAgZWF0aW5nIHNoKnQu 