# notification Service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: sagiri2k4/notification-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9006
          env:
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "broker.default.svc.cluster.local:9092"
            - name: SPRING_MAIL_HOST
              value: "smtp.gmail.com"
            - name: SPRING_MAIL_PORT
              value: "587"
            - name: SPRING_MAIL_USERNAME
              value: "it3180.devmail@gmail.com"
            - name: SPRING_MAIL_PASSWORD
              value: "yiuq gvhj bcsg kydv"
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi