apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
data:
  default.conf: |
    server {
      listen 80;
      server_name _;

      # Redirect all HTTP to HTTPS
      return 301 https://$host$request_uri;
    }

    server {
      listen 443 ssl;
      server_name _;

      ssl_certificate /etc/nginx/ssl/tls.crt;
      ssl_certificate_key /etc/nginx/ssl/tls.key;

      location /api/ {
        proxy_pass http://backend:8080/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
      }

      location /ws/ {
        proxy_pass http://notification-service:9006/ws/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
      }
    }