apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
data:
  default.conf: |
    server {
      listen 80;
      server_name _;

      location /api/ {
        proxy_pass http://backend:8080/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_intercept_errors off;
      }

      location /ws/ {
        proxy_pass http://notification-service:9006/ws/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
      }

      location / {
        return 200 "API Gateway is running!\n";
        add_header Content-Type text/plain;
      }
    }