server:
  port: 9006

spring:
  application:
    name: notification-service
  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-service