server:
  port: 8080

spring:
  application:
    name: backend
  datasource:
    url: jdbc:mysql://localhost:3306/itss_db?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
      platform: mysql
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: backend
  mail:
    host: smtp.gmail.com
    port: 587
    username: it3180.devmail@gmail.com
    password: yiuq gvhj bcsg kydv
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        transport:
          protocol: smtp

logging:
  level:
    org:
      springdoc: DEBUG


jwt:
  signerKey: "In this society, only those who work hard, diligently, and tirelessly will earn their share. Only by working can one eat. Those who expect to eat without working will end up eating sh*t."
  expirationMs: 69696969
