package com.example.backend.event.enums;

public enum NotificationType {
	INVOICE_CREATED,
	INVOICE_PAID,
	RESCUE_REQUEST,
	RESCUE_COMPLETED,
	REQUEST_ACCEPTED,
	REQUEST_CANCELED,
	VEHICLE_DISPATCHED,
	VEHICLE_ARRIVED,
	INSPECTION_COMPLETED,
	PRICE_UPDATED,
	PRICE_CONFIRMED,
	PRICE_REJECTED,
	REPAIR_STARTED,
	REPAIR_COMPLETED,
	PASSWORD_RESET,
	CHAT
}
