name: CI/CD Pipeline to GKE

on:
  push:
    branches: ["main", "ci/docker-build"]
  pull_request:
    branches: ["main", "ci/docker-build"]

env:
  PROJECT_ID: 'invertible-lens-459421-f7'
  GKE_CLUSTER: 'cluster-1'
  GKE_ZONE: 'asia-northeast1-c'
  DEPLOYMENT_NAME_BACKEND: 'backend'
  DEPLOYMENT_NAME_NOTIFICATION: 'notification-service'
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  WORKLOAD_IDENTITY_PROVIDER: 'projects/1019423138216/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
  K8S_DIR: 'k8s'

jobs:
  build:
    name: Build Docker images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: List files in the working directory
        run: ls -la
      - name: Set environment variables
        run: |
          echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}" >> $GITHUB_ENV
          echo "DOCKER_PASSWORD=${{ secrets.DOCKER_PASSWORD }}" >> $GITHUB_ENV
      - name: Install Docker Compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose
      - name: Build and tag images
        run: |
          export DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}
          docker-compose -f docker-compose.build.yml build
      - name: Push built images to Docker Hub
        run: docker-compose -f docker-compose.build.yml push

  # deploy-to-gke:
  #   name: Deploy to GKE
  #   runs-on: ubuntu-latest
  #   needs: build
  #   if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/ci/docker-build'
  #   environment: production

  #   permissions:
  #     contents: 'read'
  #     id-token: 'write'

  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4

  #     - name: Authenticate to Google Cloud
  #       id: auth
  #       uses: google-github-actions/auth@v2
  #       with:
  #         workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
  #         service_account: 'github-actions-sa@invertible-lens-459421-f7.iam.gserviceaccount.com'

  #     - name: Set up GKE credentials
  #       uses: google-github-actions/get-gke-credentials@v2
  #       with:
  #         cluster_name: ${{ env.GKE_CLUSTER }}
  #         location: ${{ env.GKE_ZONE }}

  #     - name: Install Kustomize
  #       uses: imranismail/setup-kustomize@v2
  #       with:
  #         kustomize-version: '5.4.3'

  #     - name: Update image tags in Kustomize
  #       run: |
  #         cd ${{ env.K8S_DIR }}
  #         kustomize edit set image sagiri2k4/backend=sagiri2k4/backend:latest sagiri2k4/notification-service=sagiri2k4/notification-service:latest

  #     - name: Deploy to GKE
  #       run: |
  #         cd ${{ env.K8S_DIR }}
  #         kustomize build . | kubectl apply -f -
  #         kubectl rollout status deployment/${{ env.DEPLOYMENT_NAME_BACKEND }}
  #         kubectl rollout status deployment/${{ env.DEPLOYMENT_NAME_NOTIFICATION }}
  #         kubectl get services -o wide
