name: CI/CD Pipeline to GKE

on:
  push:
    branches: ["main", "ci/docker-build"]
  pull_request:
    branches: ["main", "ci/docker-build"]

env:
  PROJECT_ID: 'invertible-lens-459421-f7'
  GKE_CLUSTER: 'cluster-1'
  GKE_ZONE: 'asia-northeast1-c'
  DEPLOYMENT_NAME_BACKEND: 'backend'
  DEPLOYMENT_NAME_NOTIFICATION: 'notification-service'
  WORKLOAD_IDENTITY_PROVIDER: 'projects/1019423138216/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
  K8S_DIR: 'k8s'
  IMAGE_BACKEND: sagiri2k4/backend
  IMAGE_NOTIFICATION: sagiri2k4/notification-service

jobs:
  build:
    name: Build Docker images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set image version tags
        run: |
          VERSION_TAG="v$(date +%Y%m%d%H%M)"  # vd: v202505151427
          echo "IMAGE_TAG=$VERSION_TAG" >> $GITHUB_ENV
          echo "Using image tag: $VERSION_TAG"

      - name: Build and tag Docker images
        run: |
          docker build -t $IMAGE_BACKEND:$IMAGE_TAG -f backend/Dockerfile .
          docker build -t $IMAGE_NOTIFICATION:$IMAGE_TAG -f notification-service/Dockerfile .

      - name: Push Docker images to Docker Hub
        run: |
          docker push $IMAGE_BACKEND:$IMAGE_TAG
          docker push $IMAGE_NOTIFICATION:$IMAGE_TAG

  deploy-to-gke:
    name: Deploy to GKE
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/ci/docker-build'
    environment: production

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: 'github-actions-sa@invertible-lens-459421-f7.iam.gserviceaccount.com'

      - name: Set up GKE credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}

      - name: Install Kustomize
        uses: imranismail/setup-kustomize@v2
        with:
          kustomize-version: '5.4.3'

      - name: Update image tags in Kustomize
        run: |
          cd ${{ env.K8S_DIR }}
          kustomize edit set image $IMAGE_BACKEND=$IMAGE_BACKEND:$IMAGE_TAG
          kustomize edit set image $IMAGE_NOTIFICATION=$IMAGE_NOTIFICATION:$IMAGE_TAG

      - name: Deploy to GKE
        run: |
          cd ${{ env.K8S_DIR }}
          kustomize build . | kubectl apply -f -
          kubectl rollout status deployment/${{ env.DEPLOYMENT_NAME_BACKEND }}
          kubectl rollout status deployment/${{ env.DEPLOYMENT_NAME_NOTIFICATION }}
